- hosts: all
  remote_user: ec2-user
  become: yes
  tasks:
   - name: Shell Module
     shell: echo "This is shell Module" > /tmp/shell_file
     register: shell_result
   - name: Command Module
     command: echo "This is Command Module" > /tmp/command_file
     register: command_result
   - name: Debug Module for Shell Module
     debug:
      var: shell_result
   - name: Debug Module for Command Module
     debug:
      var: command_result
    