- hosts: all
  remote_user: ec2-user
  become: yes
  tasks:
   - name: Multiple Installation
     yum:
      name: "{{item}}"
      state: present

     loop:
      - mysql
      - php
      - wget
      - unzip