- hosts: all
  remote_user: ec2-user
  become: yes
  tasks:

   - name: Apache Install
     yum:
      name: httpd
      state: present
   - name: Start Apache
     service:
      name: httpd
      state: started
   - name: File Copy
     copy:
      src: ./index.html
      dest: /var/www/html/index.html
      mode: "0777"